[package]
name = "jared/learningknit"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Knit = "sleitnick/knit@^1.2"
Signal = "sleitnick/signal@1.0.1"
Trove = "sleitnick/trove@0.1.3"
Timer = "sleitnick/timer@1.0.3"
Component = "sleitnick/component@2.1.0"
Option = "sleitnick/option@1.0.3"